### PR TITLE
Make it possible to have a different precision for the frontend

### PR DESCRIPTION
**Pull request by quintenbuis**
We have a client that wants to do calculation with a 4 decimal precision but only show 2 decimals on the front end. This PR will make that possible

### CODE REVIEW

**Comment by quintenbuis** [comment]
@lillik Could you take a look at this?

**Comment by VincentBean** [comment]
Would be great if this gets merged

**Comment by lillik** [comment]
@quintenbuis  nice job, thank you the code looks OK. @VincentBean It will be merged but, before, I would like to test it with a couple of Magento versions like 2.2.x, 2.3.x, and 2.4.x.

**Comment by quintenbuis** [comment]
Fixes #61

**Comment by quintenbuis** [comment]
@lillik Any idea when it will get merged?

**Comment by apohutenumera** [comment]
Hi, any news about when it will be merged ? thanks

**Comment by nelero** [comment]
Hi, any news when it will be merged ? Thank you

**Comment by quintenbuis** [comment]
@lillik Can you please merge this?

**Pull request closed without merging**
